### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by RobertMyles** [Hamurabbi/PySEAL#1]
Hi, thanks for the SEAL wrapper! I think the containerised one is a bit of work to set up, so I'm more interested in your version. Any chance of a few quick examples of how to use it?

Thanks :-)

**Comment by hammurabi-ds** [comment]
Hi Robert. Thank you, that was exactly my point, it is easier to just use this especially if experimenting in a jupyter notebook. I made this fairly quickly so the package is still not importable from any place, thus in order to use it now you have to be in the SEALPython folder. 

1. build the library. Go to scripts and run "bash build-libs.sh"
2. cd to SEALPython
3. run 'python  matrix_operations.py' which is a simple example of some matrix operations using SEAL.

Now you can also run a notebook in there to play around with PySEAL.

Best regards

**Comment by RobertMyles** [comment]
Ok, thanks @Hamurabbi!
